### PR TITLE
Port to Python 3

### PR DESCRIPTION
**Pull request by Tilka**
Python 3.5.2 is the version being tested on Travis CI. Locally I'm using Python 3.8.1 and tests pass as well.

### CODE REVIEW

**Comment by edwkmho** [comment]
i am unable to install with Ubuntu 20.04. Any help ???

**Comment by muflone** [comment]
Thank you for your contributions
I'll release a fixed Python 3 version soon

**Comment by loqs** [comment]
@muflone is the Python 3 release still planned?

**Comment by muflone** [comment]
> @muflone is the Python 3 release still planned?

sure, it is!

I totally forgot about this release. The whole code was already committed in the 5 months ago but I forgot to set a new tag and release

**Comment by muflone** [comment]
Fixed in version 0.7.0

Thank you @Tilka , I've added your name to the contributors in the about page

**Pull request merged**
